sudo: false
language: python
python:
  - 2.6
  - 2.7
install:
  - "pip install -r requirements.txt -r test_requirements.txt"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r 2.6_requirements.txt --upgrade; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls ; fi"
script:
  - ./test.sh
  - nosetests test/test_file_io.py:pack_unpack_hard
  - nosetests test/test_numpy_io.py:huge_arrays
after_success:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls ; fi"
notifications:
  email: false
