sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install .
script:
  - ./test.sh
  - nosetests test/test_file_io.py:pack_unpack_hard
after_success:
  - coveralls
notifications:
  email: false
