language: python
python:
  - 2.7
install:
  - "pip install -r test_requirements.txt --use-mirrors"
  - "python setup.py install"
script:
  - nosetests
  - ./test_bloscpack.cram
notifications:
  email: false
