language: python
python:
  - 2.6
  - 2.7
install:
  - "pip install -r test_requirements.txt --use-mirrors"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install ordereddict --use-mirrors && pip install argparse --use-mirrors; fi"
  - "pip install coveralls --use-mirrors"
  - "pip install coverage --use-mirrors"
  - "python setup.py install"
script:
  - nosetests --with-coverage --cover-package
  - ./test_bloscpack.cram
after_success:
    coveralls
notifications:
  email: false
