sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.4
install:
  - pip install .
  - pip install -r test_requirements.txt
script:
  - ./test.sh
  - nosetests test/test_file_io.py:pack_unpack_hard
  - nosetests test/test_numpy_io.py:huge_arrays
after_success:
  - coveralls
notifications:
  email: false
