language: python
python:
  - 2.6
  - 2.7
install:
  - "pip install -r test_requirements.txt --use-mirrors"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install ordereddict --use-mirrors && pip install argparse --use-mirrors; fi"
  - "pip install coveralls --use-mirrors"
script:
  - COVERAGE=1 ./test_bloscpack.cram
  - nosetests --with-coverage --cover-package=bloscpack
after_success:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls ; fi"
notifications:
  email: false
