language: python
python:
  - 2.6
  - 2.7
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test_requirements.txt --use-mirrors"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install ordereddict --use-mirrors && pip install argparse --use-mirrors; fi"
  - "pip install coveralls --use-mirrors"
script:
  - ./test.sh
  - nosetests test_bloscpack.py:pack_unpack_hard
after_success:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls ; fi"
notifications:
  email: false
