language: python
python:
  - 2.6
  - 2.7
install:
  - "pip install -r test_requirements.txt --use-mirrors"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install ordereddict --use-mirrors && pip install argparse --use-mirrors; fi"
  - "python setup.py install"
script:
  - nosetests
  - ./test_bloscpack.cram
notifications:
  email: false
