#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim :set ft=py:

import sys
import blosc

if __name__ == '__main__':
    file_name = sys.argv[1]
    input_file = open(file_name, 'r')
    plaintext = input_file.read()
    input_file.close()
    compressed = blosc.compress(plaintext, 4 ,clevel=9)
    output_file = open(file_name + '.blp', 'w')
    output_file.write(compressed)
    output_file.close()

