#!/usr/bin/env python

from __future__ import print_function
import test_bloscpack as tb

print('create the test data', end='')
def progress(i):
    if i % 10 == 0:
        print('.', end='')
    sys.stdout.flush()
tb.create_array(100, 'testfile', progress=progress)
print('')
